import type { PromptDomainLevels } from '@/lib/ai/prompt-domains';

export const defaultPromptDomainBaseline: PromptDomainLevels = {
  horniness: 2,
  boldness: 2,
  filth: 1,
  intensity: 3,
  comfort: 2,
  promiscuity: 2,
};

export const characterPromptDomainBaselines: Record<string, PromptDomainLevels> = {
  'lila-harper': {
    horniness: 3,
    boldness: 2,
    filth: 2,
    intensity: 4,
    comfort: 3,
    promiscuity: 1,
  },
  'mia-voss': {
    horniness: 4,
    boldness: 4,
    filth: 3,
    intensity: 4,
    comfort: 4,
    promiscuity: 2,
  },
  'sophia-bennett': {
    horniness: 2,
    boldness: 1,
    filth: 1,
    intensity: 4,
    comfort: 2,
    promiscuity: 1,
  },
  'raven-kane': {
    horniness: 5,
    boldness: 4,
    filth: 4,
    intensity: 3,
    comfort: 4,
    promiscuity: 4,
  },
  'isabella-morales': {
    horniness: 4,
    boldness: 4,
    filth: 3,
    intensity: 5,
    comfort: 4,
    promiscuity: 2,
  },
  'elena-voss': {
    horniness: 4,
    boldness: 2,
    filth: 2,
    intensity: 4,
    comfort: 2,
    promiscuity: 1,
  },
  'natalie-hayes': {
    horniness: 3,
    boldness: 2,
    filth: 2,
    intensity: 4,
    comfort: 2,
    promiscuity: 1,
  },
  'arabella-whitcombe': {
    horniness: 3,
    boldness: 2,
    filth: 2,
    intensity: 4,
    comfort: 3,
    promiscuity: 1,
  },
  'sophie-laurent': {
    horniness: 2,
    boldness: 1,
    filth: 1,
    intensity: 3,
    comfort: 3,
    promiscuity: 1,
  },
  'yuki-sato': {
    horniness: 5,
    boldness: 5,
    filth: 5,
    intensity: 4,
    comfort: 5,
    promiscuity: 4,
  },
  'audrey-vale': {
    horniness: 3,
    boldness: 2,
    filth: 2,
    intensity: 4,
    comfort: 3,
    promiscuity: 2,
  },
};
