import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';

import {
  companionRuntimeAssistantMessageId,
  executeCompanionRuntimeTurn,
  streamCompanionRuntimeTurn,
} from '@/lib/companion-runtime';

const input = {
  contract_version: 'v1' as const,
  turn_id: 'turn-1',
  conversation_id: 'conversation-1',
  companion_id: 'sophie' as const,
  selected_model_id: 'chat-model',
  current_sanitized_message: 'Hello',
  message_parts: [{ type: 'text', text: 'Hello' }],
  canonical_history: [],
  trusted_user_context: { user_id: 'user-1' },
  recent_provenance: {},
  capability_grant: {
    allow_read_tools: true,
    allow_live_data: true,
    allow_research: true,
    granted_scopes: ['read_tools', 'live_data', 'research'],
  },
  transcript_reliability: null,
};

// Real Companion Runtime wire shapes (generated by the Runtime's own tests).
function wire(name: string) {
  return JSON.parse(
    readFileSync(`tests/runtime-wire/${name}.json`, 'utf8'),
  );
}

const completed = {
  ...wire('completed_turn'),
  assistant_message: 'Hello back',
  beats: ['Hello back'],
  turn_id: input.turn_id,
  conversation_id: input.conversation_id,
};

const completedSingleBeat = {
  ...completed,
  beats: null,
};

function jsonResponse(value: unknown) {
  return new Response(JSON.stringify(value), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
}

test.beforeEach(() => {
  process.env.COMPANION_RUNTIME_URL = 'https://runtime.test';
  process.env.COMPANION_RUNTIME_SECRET = 'test-secret';
});

test('requires an explicit Runtime configuration; there is no native fallback', async () => {
  delete process.env.COMPANION_RUNTIME_URL;
  await expect(executeCompanionRuntimeTurn(input)).rejects.toThrow(
    /only conversational path/u,
  );
  process.env.COMPANION_RUNTIME_URL = 'https://runtime.test';
});

test('accepts the real slim completed result and carries next_session_state verbatim', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => jsonResponse(completed);
  try {
    const result = await executeCompanionRuntimeTurn(input);
    expect(result.status).toBe('completed');
    expect(result).not.toHaveProperty('decision_record');
    if (result.status === 'completed') {
      expect(result.execution_metadata.next_session_state).toEqual(
        completed.execution_metadata.next_session_state,
      );
      expect(result.beat_delivery).toEqual(completed.beat_delivery);
    }
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('accepts the real deferred tool-lane result', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => jsonResponse(wire('deferred_turn'));
  try {
    const result = await executeCompanionRuntimeTurn(input);
    expect(result.status).toBe('deferred');
    if (result.status === 'deferred') {
      expect(result.execution_lane).toBe('read_tools');
      expect(result.next_session_state).toHaveProperty('lastJev');
    }
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('accepts the production single-beat contract with explicit null beats', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => jsonResponse(completedSingleBeat);

  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(
      completedSingleBeat,
    );
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('recovers a lost POST response from durable status without another POST', async () => {
  const calls: string[] = [];
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (request) => {
    const url = String(request);
    calls.push(url);
    if (calls.length === 1) throw new TypeError('connection reset');
    return jsonResponse({ status: 'completed', result: completed });
  };

  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(
      completed,
    );
    expect(calls).toEqual([
      'https://runtime.test/v1/turns',
      'https://runtime.test/v1/turns/turn-1?conversation_id=conversation-1',
    ]);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('recovers a completed production turn whose beats are explicitly null', async () => {
  const calls: string[] = [];
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (request) => {
    calls.push(String(request));
    if (calls.length === 1) throw new TypeError('connection reset');
    return jsonResponse({ status: 'completed', result: completedSingleBeat });
  };

  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(
      completedSingleBeat,
    );
    expect(calls).toHaveLength(2);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('retries only the identical turn after status reports it still executing', async () => {
  const calls: string[] = [];
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (request) => {
    const url = String(request);
    calls.push(url);
    if (calls.length === 1) throw new TypeError('connection reset');
    if (calls.length === 2)
      return jsonResponse({ status: 'executing', result: null });
    return jsonResponse(completed);
  };

  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(
      completed,
    );
    expect(calls).toEqual([
      'https://runtime.test/v1/turns',
      'https://runtime.test/v1/turns/turn-1?conversation_id=conversation-1',
      'https://runtime.test/v1/turns',
    ]);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('retries the identical turn after a durable failed attempt', async () => {
  const calls: string[] = [];
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (request) => {
    const url = String(request);
    calls.push(url);
    if (calls.length === 1) throw new TypeError('connection reset');
    if (calls.length === 2)
      return jsonResponse({
        status: 'failed',
        result: { status: 'failed', error_code: 'PROVIDER_ERROR' },
      });
    return jsonResponse(completed);
  };

  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(
      completed,
    );
    expect(calls).toEqual([
      'https://runtime.test/v1/turns',
      'https://runtime.test/v1/turns/turn-1?conversation_id=conversation-1',
      'https://runtime.test/v1/turns',
    ]);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('derives a stable UUID-shaped assistant ID from the turn ID', () => {
  const first = companionRuntimeAssistantMessageId(
    input.conversation_id,
    input.turn_id,
  );
  expect(
    companionRuntimeAssistantMessageId(input.conversation_id, input.turn_id),
  ).toBe(first);
  expect(
    companionRuntimeAssistantMessageId(input.conversation_id, 'turn-2'),
  ).not.toBe(first);
  expect(
    companionRuntimeAssistantMessageId('conversation-2', input.turn_id),
  ).not.toBe(first);
  expect(first).toMatch(
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u,
  );
});

function sseResponse(chunks: string[]) {
  const encoder = new TextEncoder();
  return new Response(
    new ReadableStream({
      start(controller) {
        for (const chunk of chunks) controller.enqueue(encoder.encode(chunk));
        controller.close();
      },
    }),
    {
      status: 200,
      headers: { 'Content-Type': 'text/event-stream; charset=utf-8' },
    },
  );
}

test('parses split SSE frames and treats the completed result as canonical', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () =>
    sseResponse([
      ': keep-alive\r\n\r\nevent: status\r\ndata: {"contract_version":"v1","turn_id":"turn-1",',
      '"conversation_id":"conversation-1","status":"executing","phase":"context","elapsed_ms":12}\r\n\r\n',
      'event: text_delta\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","delta":"Hello ","index":0,"elapsed_ms":40}\n\n',
      `event: completed\ndata: ${JSON.stringify({
        contract_version: 'v1',
        turn_id: input.turn_id,
        conversation_id: input.conversation_id,
        result: completed,
      })}\n\n`,
    ]);

  try {
    const events = [];
    for await (const event of streamCompanionRuntimeTurn(input)) {
      events.push(event);
    }
    expect(events.map((event) => event.type)).toEqual([
      'status',
      'text_delta',
      'completed',
    ]);
    expect(events[1]?.type === 'text_delta' && events[1].data.delta).toBe(
      'Hello ',
    );
    expect(
      events[2]?.type === 'completed' &&
        events[2].data.result.status === 'completed' &&
        events[2].data.result.assistant_message,
    ).toBe('Hello back');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('rejects a stream that closes without a terminal event', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () =>
    sseResponse([
      'event: text_delta\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","delta":"partial","index":0,"elapsed_ms":40}\n\n',
    ]);

  try {
    const consume = async () => {
      for await (const _event of streamCompanionRuntimeTurn(input)) {
        // Consume the complete stream.
      }
    };
    await expect(consume()).rejects.toThrow(
      'Companion Runtime stream ended without a terminal event',
    );
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('yields a foreground delta before runtime and post-response completion', async () => {
  const originalFetch = globalThis.fetch;
  const encoder = new TextEncoder();
  let releaseCompletion: (() => void) | undefined;
  const completionGate = new Promise<void>((resolve) => {
    releaseCompletion = resolve;
  });
  globalThis.fetch = async () =>
    new Response(
      new ReadableStream({
        async start(controller) {
          controller.enqueue(
            encoder.encode(
              'event: text_delta\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","delta":"Solar first","index":0,"elapsed_ms":25}\n\n',
            ),
          );
          await completionGate;
          controller.enqueue(
            encoder.encode(
              `event: completed\ndata: ${JSON.stringify({
                contract_version: 'v1',
                turn_id: input.turn_id,
                conversation_id: input.conversation_id,
                result: completed,
              })}\n\n`,
            ),
          );
          controller.close();
        },
      }),
      { headers: { 'Content-Type': 'text/event-stream' } },
    );

  try {
    const events = streamCompanionRuntimeTurn(input);
    const first = await events.next();
    expect(first.value?.type).toBe('text_delta');
    expect(
      first.value?.type === 'text_delta' ? first.value.data.delta : null,
    ).toBe('Solar first');
    let completionObserved = false;
    const terminal = events.next().then((event) => {
      completionObserved = true;
      return event;
    });
    await new Promise((resolve) => setTimeout(resolve, 20));
    expect(completionObserved).toBe(false);
    releaseCompletion?.();
    expect((await terminal).value?.type).toBe('completed');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('parses an explicit asynchronous beat boundary without leaking a marker', async () => {
  const originalFetch = globalThis.fetch;
  const encoder = new TextEncoder();
  globalThis.fetch = async () =>
    new Response(
      new ReadableStream({
        start(controller) {
          controller.enqueue(
            encoder.encode(
              'event: text_delta\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","delta":"First beat","index":0,"elapsed_ms":25}\n\n' +
                'event: beat_start\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","beat_index":1,"elapsed_ms":80}\n\n' +
                'event: text_delta\ndata: {"contract_version":"v1","turn_id":"turn-1","conversation_id":"conversation-1","delta":"Afterthought","index":1,"elapsed_ms":82}\n\n' +
                `event: completed\ndata: ${JSON.stringify({
                  contract_version: 'v1',
                  turn_id: input.turn_id,
                  conversation_id: input.conversation_id,
                  result: completed,
                })}\n\n`,
            ),
          );
          controller.close();
        },
      }),
      { headers: { 'Content-Type': 'text/event-stream' } },
    );

  try {
    const events = [];
    for await (const event of streamCompanionRuntimeTurn(input)) {
      events.push(event);
    }
    expect(events.map((event) => event.type)).toEqual([
      'text_delta',
      'beat_start',
      'text_delta',
      'completed',
    ]);
    expect(events[1]).toMatchObject({
      type: 'beat_start',
      data: { beat_index: 1 },
    });
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('a POST that never reached the Runtime (status 404) is simply resubmitted', async () => {
  const calls: string[] = [];
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (request, init) => {
    calls.push(`${init?.method ?? 'GET'} ${String(request)}`);
    if (calls.length === 1) throw new TypeError('fetch failed');
    if (calls.length === 2) return new Response('{}', { status: 404 });
    return jsonResponse(completed);
  };
  try {
    await expect(executeCompanionRuntimeTurn(input)).resolves.toEqual(completed);
    expect(calls.map((c) => c.split(' ')[0])).toEqual(['POST', 'GET', 'POST']);
  } finally {
    globalThis.fetch = originalFetch;
  }
});
